# Site settings
title: Integration Guides for Using Solace Messaging
baseurl: "/solace-integration-guides" # the subpath of your site, e.g. /solace-samples-java
repository: https://github.com/SolaceLabs/solace-integration-guides

# Also see _includes/intro.html to customize the description which gets included in index.html.

# Links
links-vmr-setup: https://docs.solace.com/Solace-SW-Broker-Set-Up/Setting-Up-SW-Brokers.htm
links-solaceCloud-setup: //cloud.solace.com/create-messaging-service/
links-dev-portal: http://dev.solace.com
links-docs-jms: http://docs.solace.com/Solace-JMS-API/JMS-home.htm
links-docs-jms-api: http://docs.solace.com/API-Developer-Online-Ref-Documentation/jms/index.html
links-docs-jms-properties: https://docs.solace.com/Solace-JMS-API/JMS-Properties-Reference.htm
links-docs-features: https://docs.solace.com/Features/Core-Concepts.htm
links-docs-router-config: http://docs.solace.com/Router-Configuration.htm
links-docs-config-server-cert: https://docs.solace.com/Configuring-and-Managing/Managing-Server-Certs.htm
links-docs-cli: https://docs.solace.com/Solace-CLI/Using-Solace-CLI.htm
links-docs-user-authenticate-authorize: https://docs.solace.com/Features/Mgmt-User-Authenticate-Authorize.htm
links-docs-client-authenticate-authorize: https://docs.solace.com/Features/Client-authentication-and-authorization.htm
links-downloads: https://solace.com/downloads/
links-vmr-getstarted: http://dev.solace.com/get-started/start-up-solace-messaging/
links-jms-maven: https://mvnrepository.com/artifact/com.solacesystems/sol-jms
links-jms-cust-rar-download: https://products.solace.com
links-contact-psg: http://dev.solace.com/contact-us/
links-docs-webadmin: https://docs.solace.com/Solace-PubSub-Manager/PubSub-Manager-Overview.htm
links-docs-replication: https://docs.solace.com/Features/Data-Center-Replication.htm
links-docs-replication-client-config: https://docs.solace.com/Features/Data-Center-Replication.htm#Client_Configuration
links-liberty-reference: https://www.ibm.com/cloud/websphere-liberty
links-was-reference: https://www.ibm.com/support/knowledgecenter/SSEQTP/mapfiles/product_welcome_was.html
links-jboss-modules: https://jboss-modules.github.io/jboss-modules/manual
links-jboss-modules-file-system: https://jboss-modules.github.io/jboss-modules/manual/#basic-repository
links-springfw-four: https://docs.spring.io/spring/docs/4.3.0.RELEASE/spring-framework-reference/html/
links-springfw-five: https://docs.spring.io/spring/docs/5.1.4.RELEASE/spring-framework-reference/
links-springfw-five-java-based-container: https://docs.spring.io/spring/docs/5.1.4.RELEASE/spring-framework-reference/core.html#beans-java
links-springfw-five-integration: https://docs.spring.io/spring/docs/5.1.4.RELEASE/spring-framework-reference/integration.html
links-springfw-five-jms: https://docs.spring.io/spring/docs/5.1.4.RELEASE/spring-framework-reference/integration.html#remoting-jms
links-springfw-five-async-reception: https://docs.spring.io/spring/docs/5.1.4.RELEASE/spring-framework-reference/integration.html#jms-asynchronousMessageReception
links-springfw-five-jms-template: https://docs.spring.io/spring/docs/5.1.4.RELEASE/spring-framework-reference/integration.html#jms-jmstemplate
links-springfw-five-jms-dest-mgmt: https://docs.spring.io/spring/docs/5.1.4.RELEASE/spring-framework-reference/integration.html#jms-destinations
links-springfw-four-logging: https://docs.spring.io/spring/docs/4.3.0.RELEASE/spring-framework-reference/htmlsingle/#overview-logging 





#----------------------------------------------------
# Generally don't modify items below this point
url: "solacelabs.github.io" # the base hostname & protocol for your site

# Google services
google_analytics: UA-3921398-7

# Build settings
markdown: kramdown

collections:
  guides:
    output: true
    permalink: /:path/
